config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :operations, only: :index
  resources :companies, only: :index do
    resources :files, only: :create
  end
  resources :imports, only: [:create, :new]

  resource :search, only: :search do
    get :search
  end

  root to: "companies#index"
end

app/models/categories_operation.rb
class CategoriesOperation < ActiveRecord::Base
  belongs_to :category
  belongs_to :operation

  validates_presence_of :category_id, :operation_id
  validates :category_id, uniqueness: { scope: :operation_id  }
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categories_operations, dependent: :destroy
  has_many :operations, through: :categories_operations
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/company.rb
require 'csv'
class Company < ActiveRecord::Base
  has_many :operations
  validates_presence_of :name

  def operations_number
    operations.count
  end

  def average_amount
    operations.average('amount')
  end

  def accepted_operations_num
    operations.where(status: 'accepted').count
  end

  def highest_month_operations
    operation =  operations.where(operation_date: Date.today.beginning_of_month..Date.today.end_of_month,
                            amount: operations.maximum(:amount)).first
      operation ? operation.amount : 0
  end

  def create_operations_csv(source)
    CSV.open(source.path, "wb") do |csv|
      csv << %w(company invoice_num invoice_date operation_date amount reporter notes status kind)
      operations.each do |operation|
        csv << [self.name,
                operation.invoice_num,
                operation.invoice_date,
                operation.operation_date,
                operation.amount,
                operation.reporter,
                operation.notes,
                operation.status,
                operation.kind
        ]
      end
    end
  end
end

app/models/import.rb
class Import < ActiveRecord::Base
  mount_uploader :file, FileUploader
  validates :file, presence: true

  def init_import!
    ImportService.new(self.file.current_path).perform!
  end
end

app/models/operation.rb
class Operation < ActiveRecord::Base
  has_many :categories_operations, dependent: :destroy
  has_many :categories, through: :categories_operations
  belongs_to :company

  validates_numericality_of :amount, greater_than: 0
  validates :invoice_num, uniqueness: true
  validates_presence_of :company_id, :invoice_num, :invoice_date,
                        :amount, :operation_date, :kind, :status

  def add_categories!
    define_categories
  end

  private
  def define_categories
    name_list = kind.split(';').map! { |name| name.capitalize }.uniq
    present_categories = Category.where(name: name_list)
    name_list -= present_categories.pluck(:name)

    create_missing_categories_by(name_list)
    add_present_categories(present_categories)
  end

  def create_missing_categories_by(name_list)
    name_list.each do |name|
      categories.create(name: name)
    end
  end

  def add_present_categories(categories_list)
    categories_list.each do |category|
      categories_operations.create(category_id: category.id)
    end
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  respond_to :json

  def index
    @companies = Company.all
    respond_with(@companies)
  end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  before_action :set_company
  before_action :set_file

  def create
    @company.create_operations_csv(@file)
    send_file_to_download
  end

  private
  def set_company
    @company = Company.find(params[:company_id])
  end

  def set_file
    @file = Tempfile.new(["#{@company.name}_operations", '.csv'])
  end

  def send_file_to_download
    send_file File.join(@file.path)
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :check_import
  respond_to :json

  def create
    @import = Import.create(import_params)
    ImportJob.perform_later(@import)
    redirect_to companies_path
  end

  private
  def check_import
    render json: {message: 'No file'} unless params[:import]
  end

  def import_params
    params.require(:import).permit(:file)
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  respond_to :json

  def index
    @operations = Operation.all
    respond_with(@operations)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :init_search, only: :search
  respond_to :json

  def search
    @result = @search.result
    respond_with (@result)
  end

  private
  def init_search
    @search = SearchService.new(query, category)
  end

  def query
    params[:query]
  end

  def category
    params[:category]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/index.html.slim
.container-fluid
  .row
    .errors
    .col-lg-9
      = form_tag search_search_path, method: :get, class: 'import_form', remote: true, data: {type: :json} do
        .col-lg-3
          = select_tag :category, options_for_select(['Company', 'Operation']), class: 'form-control'
        .col-lg-7
          = search_field_tag :query, '', class: 'form-control', placeholder: 'Please write text for search'
        .col-lg-2
          = submit_tag "Get Operations", class: 'btn btn-primary', id: 'search_button'
    .col-lg-3
      .row
        = form_for Import.new, method: :post, target: '_self', remote: true do |f|
          .col-lg-7
            = f.file_field :file, class: 'form-control'
          .col-lg-3
            = f.submit 'Import', class: 'btn btn-info'
      br
      hr
      .row.import_info.btn-warning
      hr
      br
      .row.import_info_status.btn-warning
      hr

  .row
    javascript:
      var socket = new WebSocket("ws://127.0.0.1:9000");

      socket.onopen = function () {
        $('.import_info').html('The connection by WebSocket established');
      };

      socket.onclose = function (event) {
        if (event.wasClean) {
          $('.import_info').html('Connection is closed');
        } else {
          $('.import_info').html('Connection is interrupted');
        }
      };

      socket.onmessage = function (event) {
        $('.import_info_status').html('Received data ' + event.data);
      };

      socket.onerror = function (error) {

      };
    br
  .row.companies

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "ImportApp"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    /= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
      /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

  body
    .navbar.btn-warning
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
        a.navbar-brand href="#"ImportApp
    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield
      footer
        p &copy; Company 2016